Abrindo questao
Estevam1to/qxcode pull request #60
Opened 2023-11-26 20:21 UTC by kairosb

2023-11-26 23:52 UTC, GuthyerriAlexandrino requested changes

2023-11-26 23:52 UTC, GuthyerriAlexandrino commented on qxcode-codigo/src/main/java/com/qxcode/Controller/ControllerQuestion.java
> +    public List<Question> getQuestionByCategory(int category) {
Use enum ao invés de int

2023-11-27 02:09 UTC, GuthyerriAlexandrino approved these changes

2023-11-27 02:13 UTC, Estevam1to approved these changes

2023-11-27 02:14 UTC, merged